name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2023-07-28"
kv_namespaces = [
    { binding = "KV", id = "20c19e4d303847c89a3296acb06eb161", preview_id = "20c19e4d303847c89a3296acb06eb161" }
]
